/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#301400',
        'on-secondary-fixed-variant': '#5516be',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#494bd6',
        'on-primary-container': '#fffbff',
        'primary-container': '#6063ee',
        'on-secondary-container': '#fffbff',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#ffb783',
        'secondary': '#6b38d4',
        'surface-dim': '#d8dadc',
        'surface-container': '#eceef0',
        'secondary-container': '#8455ef',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-fixed-variant': '#703700',
        'surface': '#f7f9fb',
        'on-error': '#ffffff',
        'primary': '#4648d4',
        'error-container': '#ffdad6',
        'primary-fixed': '#e1e0ff',
        'tertiary': '#904900',
        'on-error-container': '#93000a',
        'outline-variant': '#c7c4d7',
        'inverse-surface': '#2d3133',
        'error': '#ba1a1a',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed-variant': '#2f2ebe',
        'inverse-primary': '#c0c1ff',
        'outline': '#767586',
        'on-background': '#191c1e',
        'tertiary-fixed': '#ffdcc5',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#07006c',
        'secondary-fixed': '#e9ddff',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed': '#23005c',
        'background': '#f7f9fb',
        'primary-fixed-dim': '#c0c1ff',
        'on-surface-variant': '#464554',
        'surface-variant': '#e0e3e5',
        'tertiary-container': '#b55d00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
